### ISSUE TITLE
Error displaying first line of post on Safari for Mac

### ISSUE THREAD

**Issue by bapfeld** [ferrolho/jekyll-theme-libretto#4]
The first line of text for each post disappears on Safari for Mac. Apparently this was a problem in the original Wordpress theme too: https://en.forums.wordpress.com/topic/libretto-theme-not-displaying-properly-in-safari.  Here's their solution in their style.css file:

```css
/*
Browser hack that targets Safari only, to prevent first line from disappearing.
See: https://stackoverflow.com/questions/16348489/is-there-a-css-hack-for-safari-only-not-chrome
*/
@media not all and (min-resolution:.001dpcm) { @media {
    .format-standard:not(.post-password-required) .entry-content > p:not(.no-emphasis):first-of-type::after,
	.page:not(.post-password-required) .entry-content > p:not(.no-emphasis):first-of-type::after,
	.emphasis::after {
		display: inline-block;
	}
}}
```

I don't know enough about scss to incorporate this or I'd do it myself and submit a PR.
